{% set name = "s3path" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1a8cfeff71533cf5d97bde2855d9df336daa7b157e238faa8022abd7fba2842e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - python >=3.5
    - boto3 >=1.16.35
    - smart_open

test:
  imports:
    - s3path

about:
  home: https://github.com/liormizr/s3path
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Pathlib Extension for AWS S3 Service, to provide File-System/Path like interface

extra:
  recipe-maintainers:
    - liormizr
