{% set name = "s3path" %}
{% set version = "0.6.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/liormizr/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 9036c9308d00ebc7fb707093ecf6d5edc232d8f99bd411f4c7afe95a98af6665

build:
  number: 0
  skip: True  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools
  run:
    - python
    - boto3 >=1.16.35
    - smart_open >=5.1.0

test:
  source_files:
    - tests
  imports:
    - s3path
  requires:
    - pip
    - pytest
    - moto
  commands:
    - pip check
    - pytest -v # [py<312]
    # Failed: DID NOT WARN. No warnings of type (<class 'DeprecationWarning'>, <class 'PendingDeprecationWarning'>, <class 'FutureWarning'>) were emitted.
    - pytest -v -k "not (test_glob_old_algo or test_rglob_old_algo or test_accessor_scandir_old_algo)" # [py>=312 and unix]
    # NotImplementedError: cannot instantiate 'PosixPath' on your system
    - pytest -v -k "not (test_glob_old_algo or test_rglob_old_algo or test_accessor_scandir_old_algo or test_walk or test_walk_order)" # [py>=312 and win]

about:
  home: https://github.com/liormizr/s3path
  dev_url: https://github.com/liormizr/s3path
  doc_url: https://github.com/liormizr/s3path/blob/master/README.rst
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Pathlib Extension for AWS S3 Service, to provide File-System/Path like interface
  description: |
    S3Path provide a Python convenient File-System/Path like interface for AWS S3 Service 
    using boto3 S3 resource as a driver.

extra:
  recipe-maintainers:
    - liormizr
